title: susan evans.
email: hello@susanev.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the online portfolio of susan evans&mdash;a full-stack designer, and computer science educator.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://susanrevans.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: susan__ev
github_username:  susanev

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
